### ISSUE TITLE
Not working with react-native 0.59

### ISSUE THREAD

**Issue by sapjax** [awesomejerry/react-native-qrcode-svg#58]
method.bind is not a function

**Comment by awesomejerry** [comment]
I tried with react-native@0.59.9 and it's working. Are you sure that it's related to react-native version?

**Comment by aijason** [comment]
![image](https://user-images.githubusercontent.com/13975853/60067430-11dce800-973d-11e9-99d9-b8522bcf8822.png)
on react-native@0.59.9

**Comment by aijason** [comment]
"react-native-qrcode-svg": "^5.0.6",

**Comment by aijason** [comment]
Upgrading to the latest version is no problem
```
"react-native-svg": "^9.5.1"，
"react-native-qrcode-svg": "^5.1.2",
```
